apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-07-30T22:07:19Z"
  generation: 1
  labels:
    app: php-management-data-web
  name: php-management-data-web
  namespace: default
  resourceVersion: "26448"
  selfLink: /apis/apps/v1/namespaces/default/deployments/php-management-data-web
  uid: 5465dc82-d5ff-429e-851b-dc3a178e52fb
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: php-management-data-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: php-management-data-web
    spec:
      containers:
      - image: caprilespe/php-management-data-web:v1
        imagePullPolicy: IfNotPresent
        name: php-management-data-web
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-07-30T22:07:53Z"
    lastUpdateTime: "2021-07-30T22:07:53Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-07-30T22:07:19Z"
    lastUpdateTime: "2021-07-30T22:07:53Z"
    message: ReplicaSet "php-management-data-web-7f86b85d88" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
