apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-07-30T22:10:47Z"
  labels:
    app: php-management-data-web
  name: php-management-data-web
  namespace: default
  resourceVersion: "26573"
  selfLink: /api/v1/namespaces/default/services/php-management-data-web
  uid: 47f6a546-e265-4742-b8ed-f7e13f048f35
spec:
  clusterIP: 10.107.149.60
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31040
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: php-management-data-web
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
